services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: grades
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./sql_scripts:/docker-entrypoint-initdb.d

  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: grades
      DB_USER: postgres
      DB_PASSWORD: password

volumes:
  postgres_data:
